name: UI Test

on: [push, pull_request]

jobs:
  ui-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start Flask app
      run: |
        python webapp/app.py &
        sleep 5

    - name: Run Selenium UI Tests
      run: |
        pytest tests/test_ui.py
